FROM solr:8.3
ENV SOLR_USER="solr" \
    SOLR_GROUP="solr"
USER root
COPY --chown=solr:solr ./config/security.json /var/solr/data/security.json
COPY --chown=solr:solr ./config/managed-schema.xml .
USER $SOLR_USER