version: '3'
services:
  ecm-fp-service-dev:
    image: ecm-fp-service:dev
    build: 
      context: .
      dockerfile: Dockerfile.fp-service
    restart: always
    expose:
      - "5051"
    ports:
      - "5051:5051"
    volumes:
      - /home/centos/ecm-file-uploads:/uploads
    networks:
      - ecm-dev-network
