version: '3.4'

networks:
    ecm-dev-network:
        external: true

services:
  ecm-postgres:
    image: postgres:15.3
    container_name: ecm-postgres-dev
    restart: always
    ports:
      - "54329:5432"
    command: postgres -c 'max_connections=300'
    environment:
      POSTGRES_USER: ecm
      POSTGRES_PASSWORD: P@ssw0rd!
      TZ: Asia/Jakarta
    volumes:
      - ecm-postgres-data-dev:/var/lib/postgresql/data
    networks:
      - ecm-dev-network
      
  ecm-solr:
    image: solr:8.11.2
    container_name: ecm-solr-dev
    user: "solr:solr"
    ports:
     - "7983:8983"
    restart: always
    environment:
      - TZ=Asia/Jakarta
      - SOLR_USER=solr
      - SOLR_GROUP=solr
    volumes:
      - ./config/security.json:/var/solr/data/security.json
      - ./config/managed-schema.xml:/managed-schema.xml
      - ecm-solr-data-dev:/var/solr
    command: >
      sh -c "precreate-core document; cp managed-schema.xml /var/solr/data/document/conf/managed-schema; precreate-core document_bundle; cp managed-schema.xml /var/solr/data/document_bundle/conf/managed-schema; precreate-core folder; cp managed-schema.xml /var/solr/data/folder/conf/managed-schema; exec solr -f"
    networks:
      - ecm-dev-network
  
  ecm-redis:
    image: bitnami/redis:latest
    container_name: ecm-redis-dev
    ports:
     - "6379:6379"
    restart: always
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=P@ssw0rd!
      - TZ=Asia/Jakarta
    volumes:
      - ecm-redis-data-dev:/data
    networks:
      - ecm-dev-network

  ecm-admin-service:
    image: openjdk:17-alpine
    container_name: ecm-admin-service-dev
    restart: always
    expose:
      - "5050"
    ports:
      - "5050:5050"
    networks:
      - ecm-dev-network
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./apps/admin-service.jar:/app/admin-service.jar
    command: >
      sh -c "java -jar /app/admin-service.jar"

  ecm-fp-service:
    image: openjdk:17-alpine
    container_name: ecm-fp-service-dev
    restart: always
    expose:
      - "5051"
    ports:
      - "5051:5051"
    networks:
      - ecm-dev-network
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./apps/fp-service.jar:/app/fp-service.jar
      - /home/centos/ecm-file-uploads:/uploads
    command: >
      sh -c "apk add --no-cache fontconfig ttf-dejavu && java -jar /app/fp-service.jar"

  ecm-frontend:
    image: nginx:alpine
    container_name: ecm-frontend-dev
    restart: always
    expose:
      - "80"
    ports:
      - "6080:80"
    networks:
      - ecm-dev-network
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - ./apps/frontend.tar.gz:/app/frontend.tar.gz
    command: >
      sh -c "apk add --no-cache tzdata && tar -xf /app/frontend.tar.gz -C /usr/share/nginx/html/ && nginx -g 'daemon off;'"

volumes:
  ecm-solr-data-dev: 
  ecm-postgres-data-dev:
  ecm-redis-data-dev:
