version: '3.4'

networks:
    ecm-dev-network:
        external: true

services:
  ecm-admin-service:
    image: ecm-admin-service:dev
    container_name: ecm-admin-service-dev
    build:
      context: .
      dockerfile: Dockerfile.admin-service
    restart: always
    expose:
      - "5050"
    ports:
      - "5050:5050"
    networks:
      - ecm-dev-network

  ecm-fp-service:
    image: ecm-fp-service:dev
    container_name: ecm-fp-service-dev
    build: 
      context: .
      dockerfile: Dockerfile.fp-service
    restart: always
    expose:
      - "5051"
    ports:
      - "5051:5051"
    volumes:
      - /home/centos/ecm-file-uploads:/uploads
    networks:
      - ecm-dev-network

  ecm-frontend:
    image: ecm-frontend:dev
    container_name: ecm-frontend-dev
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    expose:
      - "80"
    ports:
      - "6080:80"
    networks:
      - ecm-dev-network
