#Where we start
FROM nginx:1.17.1-alpine

#Set timezone
RUN apk add tzdata
ENV TZ=Asia/Jakarta

#Get APK up to date
RUN apk update && apk upgrade

#Git
RUN apk add git
RUN mkdir /app
RUN git clone https://github.com/akbartrinanda/jar /app

COPY nginx.conf /etc/nginx/nginx.conf
COPY /app/dist /usr/share/nginx/html

EXPOSE 8080