version: '3'
services:
  ecm-frontend-dev:
    image: ecm-frontend:dev
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    expose:
      - "80"
    ports:
      - "6080:80"
    networks:
      - ecm-dev-network
