FROM nginx:alpine

RUN apk add --no-cache tzdata
ENV TZ Asia/Jakarta

WORKDIR /app
COPY ./apps/frontend.tar.gz .
RUN tar -xf frontend.tar.gz -C /usr/share/nginx/html/
# RUN mkdir -p /etc/nginx/html
# RUN tar -xf frontend.tar.gz -C /etc/nginx/html/
# COPY ./config/nginx.conf /etc/nginx/conf.d/nginx.conf
# COPY ./certs /etc/nginx/certs
