version: '3'
services:
  ecm-admin-service-dev:
    image: ecm-admin-service:dev
    build:
      context: .
      dockerfile: Dockerfile.admin-service
    restart: always
    expose:
      - "5050"
    ports:
      - "5050:5050"
    networks:
      - ecm-dev-network
