FROM openjdk:8-alpine

RUN apk add --no-cache fontconfig ttf-dejavu
RUN apk add --no-cache tzdata
ENV TZ Asia/Jakarta

WORKDIR /app
COPY ./apps/fp-service.jar .

ENTRYPOINT ["java", "-jar", "fp-service.jar"]