#Where we start
FROM openjdk:12-alpine AS builder

#Set timezone
RUN apk add tzdata
ENV TZ=Asia/Jakarta

#Get APK up to date
RUN apk update && apk upgrade

#Git
RUN apk add git
RUN mkdir /app
RUN git clone https://github.com/akbartrinanda/jar /app

# Build release image
FROM openjdk:12-alpine

#Copy result
WORKDIR /executables
COPY --from=builder /app/dev .

#Add user and group for running as unprivileged user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

#Define how to start
ENTRYPOINT ["java", "-jar", "fp-service-1.0.0.jar"]

EXPOSE 7071