version: '3'
services:
  solr-bssn:
    image: solr
    container_name: solr-bssn
    build: 
      context: .
      dockerfile: Dockerfile.solr
    ports:
     - "7983:8983"
    restart: always
    environment:
      TZ: Asia/Jakarta
    volumes:
      - solr-data-bssn:/var/solr
    command: >
      sh -c "precreate-core document; precreate-core document_bundle; precreate-core folder; cp managed-schema.xml /var/solr/data/document/conf/managed-schema; cp managed-schema.xml /var/solr/data/document_bundle/conf/managed-schema; cp managed-schema.xml /var/solr/data/folder/conf/managed-schema; exec solr -f"
  postgres-bssn:
    image: postgres
    container_name: postgres-bssn
    ports:
     - "54329:5432"
    restart: always
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: bssn
      POSTGRES_PASSWORD: P@ssw0rd!
      TZ: Asia/Jakarta
    volumes:
      - postgres-data-bssn:/var/lib/postgresql/data
  redis-bssn:
    image: bitnami/redis:latest
    container_name: redis-bssn
    ports:
     - "6379:6379"
    restart: always
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=P@ssw0rd!
      - TZ=Asia/Jakarta
    volumes:
      - redis-data-bssn:/data
volumes:
  solr-data-bssn: 
  postgres-data-bssn:
  redis-data-bssn:
