FROM nginx:alpine

RUN apk add --no-cache tzdata
ENV TZ Asia/Jakarta

WORKDIR /executables
COPY ./apps/frontend-v2.tar.gz .
RUN tar -xf frontend-v2.tar.gz -C /usr/share/nginx/html/
RUN mkdir -p /etc/nginx/html
RUN tar -xf frontend-v2.tar.gz -C /etc/nginx/html/
COPY ./config/nginx.conf /etc/nginx/conf.d/nginx.conf
COPY ./certs /etc/nginx/certs