FROM nginx:alpine

RUN apk add --no-cache tzdata
ENV TZ Asia/Jakarta

WORKDIR /executables
COPY ./apps/frontend-ocr.tar.gz .
RUN tar -xf frontend-ocr.tar.gz -C /usr/share/nginx/html/
RUN mkdir -p /etc/nginx/html
RUN tar -xf frontend-ocr.tar.gz -C /etc/nginx/html/
