version: '3'
services:
  fp-service-bssn:
    image: fp-service-bssn
    build: 
      context: .
      dockerfile: Dockerfile.fp-service
    restart: always
    expose:
      - "5051"
    ports:
      - "5051:5051"
    volumes:
      - /home/user/uploads-bssn:/uploads
