version: '3'
services:
  fp-service-bssn:
    image: fp-service-bssn
    build: 
      context: .
      dockerfile: Dockerfile.fp-service
    restart: always
    expose:
      - "5051"
    ports:
      - "5051:5051"
    volumes:
      - /home/user/uploads-bssn:/uploads
  frontend-bssn:
    image: frontend-bssn
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - "5080:80"
      - "5443:443"
  frontend-v2-bssn:
    image: frontend-v2-bssn
    build: 
      context: .
      dockerfile: Dockerfile.frontend-v2
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - "6080:80"
      - "6443:443"
