FROM openjdk:17-oracle

# Change timezone to Asia/Jakarta
RUN ln -snf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && echo Asia/Jakarta > /etc/timezone

WORKDIR /app
COPY ./apps/admin-service.jar .

ENTRYPOINT ["java", "-jar", "admin-service.jar"]