# Build release image
FROM openjdk:12-alpine

#Copy result
WORKDIR /executables
COPY fp-service.jar .

#Add user and group for running as unprivileged user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

#Define how to start
ENTRYPOINT ["java", "-jar", "fp-service.jar"]

EXPOSE 7071