FROM nginx:alpine

WORKDIR /executables
COPY ./apps/frontend.tar.gz .
RUN tar -xf frontend.tar.gz -C /usr/share/nginx/html/
# COPY nginx.conf /etc/nginx/conf.d/nginx.conf
# COPY ./certs /etc/nginx/certs