# stage 1
FROM node:alpine AS builder
RUN apk add git
RUN git clone https://github.com/akbartrinanda/jar /app

# stage 2
FROM nginx:alpine

WORKDIR /executables
COPY --from=builder /app/dev/application-host/dist .
COPY /dist/ /usr/share/nginx/html

EXPOSE 80